FROM eclipse-temurin:25-jdk-alpine

WORKDIR /app
COPY mvnw pom.xml ./
COPY .mvn .mvn
RUN chmod +x mvnw
COPY src ./src
RUN ./mvnw -q -DskipTests package

EXPOSE 8081
CMD ["java", "-jar", "target/feedlytics-service-0.0.1-SNAPSHOT.jar"]
