services:
  redis:
    image: redis:7-alpine
    container_name: feedlytics-redis-dev
    command: ["redis-server", "--requirepass", "redispass"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  feedlytics-queue-service:
    build:
      context: ./feedlytics-queue-service
      dockerfile: Dockerfile.dev
    container_name: feedlytics-queue-service-dev
    env_file:
      - .env.development
    environment:
      REDIS_URL: redis://default:redispass@redis:6379
      NODE_ENV: development
    ports:
      - "3001:3001"
      - "9090:9090"
    volumes:
      - ./feedlytics-queue-service:/app
      - queue_node_modules:/app/node_modules
    networks:
      - app-network

  feedlytics-service:
    build:
      context: ./feedlytics-service
      dockerfile: Dockerfile.dev
    container_name: feedlytics-service-dev
    env_file:
      - .env.development
    environment:
      REDIS_URL: redis://default:redispass@redis:6379
      GRPC_CLIENT_FEEDLYTICSQUEUE_ADDRESS: static://feedlytics-queue-service:9090
      FEEDLYTICS_QUEUE_CALLBACK_BASE_URL: http://feedlytics-service:8081
    ports:
      - "8081:8081"
    networks:
      - app-network

  feedlytics-dashboard:
    build:
      context: ./feedlytics-dashboard
      dockerfile: Dockerfile.dev
    container_name: feedlytics-dashboard-dev
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./feedlytics-dashboard:/app
      - dashboard_node_modules:/app/node_modules
    networks:
      - app-network

  feedlytics-widget:
    build:
      context: ./feedlytics-widget
      dockerfile: Dockerfile.dev
    container_name: feedlytics-widget-dev
    env_file:
      - .env.development
    ports:
      - "4173:4173"
    volumes:
      - ./feedlytics-widget:/app
      - widget_node_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redisdata:
  queue_node_modules:
  dashboard_node_modules:
  widget_node_modules:
