services:
  nextjs:
    image: aniii1802/feedlytics-nextjs:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - services
      - redis
    env_file:
      - .env

  services:
    image: aniii1802/feedlytics-services:latest
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  widget:
    image: aniii1802/feedlytics-widget:latest
    restart: always
    ports:
      - "4173:4173"
    networks:
      - app-network
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: feedlytics-redis
    restart: always
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge