services:
  nextjs:
    image: aniii1802/feedlytics-nextjs:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - services
      - redis
    env_file:
      - .env

  services:
    image: aniii1802/feedlytics-services:latest
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  widget:
    image: aniii1802/feedlytics-widget:latest
    restart: always
    ports:
      - "4173:4173"
    networks:
      - app-network
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: feedlytics-redis
    restart: always
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: feedlytics-prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=1GB"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: feedlytics-grafana
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: feedlytics-node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  prometheusdata:
  grafanadata:
