FROM node:18-alpine

RUN apk add --no-cache postgresql-client redis bash git
RUN npm config set strict-ssl false && npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* tsconfig.json* .npmrc ./
RUN pnpm install --frozen-lockfile

ENV NODE_ENV=development
EXPOSE 3001

CMD ["pnpm", "run", "dev"]
