# Start with the base image
FROM node:18-alpine

# Install necessary tools
RUN apk add --no-cache bash git
RUN npm config set strict-ssl false && npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy dependency manifests and .npmrc
COPY package.json pnpm-lock.yaml* .npmrc ./

# Install dependencies. This layer is cached and only re-runs if your manifests change.
RUN pnpm install --frozen-lockfile

# Expose the port
ENV PORT=3000
EXPOSE 3000

# The command to start the development server
CMD ["pnpm", "dev"]