FROM node:20-alpine

RUN apk add --no-cache bash git
RUN npm config set strict-ssl false && npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* .npmrc ./
RUN pnpm install --frozen-lockfile

ENV PORT=3000
EXPOSE 3000

CMD ["pnpm", "dev"]
