FROM node:18-alpine

RUN apk add --no-cache bash git
RUN npm config set strict-ssl false && npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* .npmrc ./
RUN pnpm install --frozen-lockfile

ENV PORT=4173
EXPOSE 4173

CMD ["pnpm", "run", "dev"]
