services:
  nextjs:
    image: aniii1802/feedlytics-nextjs:latest
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "3000:3000"

  services:
    image: aniii1802/feedlytics-services:latest
    networks:
      - app-network
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "3001:3001"

  widget:
    image: aniii1802/feedlytics-widget:latest
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "4173:4173"

  redis:
    image: redis:7-alpine
    container_name: feedlytics-redis
    restart: always
    command: redis-server --requirepass redispass
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
