global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prom-server:9090"]

  - job_name: "nextjs"
    static_configs:
      - targets: ["nextjs:3000"]
