import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import { MessageProvider } from "../../../context/MessageProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en">
      <AuthProvider>
        <div className={`${inter.className} flex bg-[#f5f5f5]`}>
          <Navbar />
          <MessageProvider>
            <main className=" overflow-y-auto w-[90%] max-sm:w-[95%] max-sm:mx-auto sm:ml-64">
              {children}
            </main>
          </MessageProvider>
          <Toaster />
        </div>
      </AuthProvider>
    </main>
  );
}
