name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

env:
  DOCKER_USERNAME: aniii1802
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Next.js
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t $DOCKER_USERNAME/feedlytics-nextjs:latest ./Next
          docker push $DOCKER_USERNAME/feedlytics-nextjs:latest

      - name: Build and push Services
        run: |
          docker build -t $DOCKER_USERNAME/feedlytics-services:latest ./Services
          docker push $DOCKER_USERNAME/feedlytics-services:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd feedlytics/
            docker rmi -f $(docker images -q) || true
            docker-compose down || true
            docker-compose up -d --pull always
