name: Sync Config to VPS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to sync from"
        required: true
        default: "master"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Sync config files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_VPS_HOST }}
          username: ${{ secrets.HOSTINGER_VPS_USER }}
          key: ${{ secrets.HOSTINGER_VPS_PVT_KEY }}
          source: "docker-compose.yml,monitoring/"
          target: "~/feedlytics"

      - name: Restart containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_VPS_HOST }}
          username: ${{ secrets.HOSTINGER_VPS_USER }}
          key: ${{ secrets.HOSTINGER_VPS_PVT_KEY }}
          script: |
            cd feedlytics/
            docker compose up -d --force-recreate
            docker image prune -f
