import type { FormTheme } from "@/lib/theme-utils";

export interface ThemePreset {
  name: string;
  theme: FormTheme;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: "Minimal Light",
    theme: {
      formBgColor: "#FFFFFF",
      formTextColor: "#1A1A1A",
      accentColor: "#6366F1",
      inputBgColor: "#F9FAFB",
      inputBorderColor: "#E5E7EB",
      inputTextColor: "#111827",
      secondaryTextColor: "#6B7280",
      fontFamily: "Inter",
      borderRadius: 12,
      shadow: "none",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Minimal Dark",
    theme: {
      formBgColor: "#0F0F0F",
      formTextColor: "#F5F5F5",
      accentColor: "#818CF8",
      inputBgColor: "#1C1C1C",
      inputBorderColor: "#2E2E2E",
      inputTextColor: "#F5F5F5",
      secondaryTextColor: "#A1A1AA",
      fontFamily: "Inter",
      borderRadius: 12,
      shadow: "subtle",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Ocean",
    theme: {
      formBgColor: "#0C1B33",
      formTextColor: "#E0F2FE",
      accentColor: "#38BDF8",
      inputBgColor: "#112240",
      inputBorderColor: "#1E3A5F",
      inputTextColor: "#E0F2FE",
      secondaryTextColor: "#7DD3FC",
      fontFamily: "DM Sans",
      borderRadius: 16,
      shadow: "medium",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Sunset",
    theme: {
      formBgColor: "#FFF7ED",
      formTextColor: "#431407",
      accentColor: "#F97316",
      inputBgColor: "#FFEDD5",
      inputBorderColor: "#FDBA74",
      inputTextColor: "#431407",
      secondaryTextColor: "#9A3412",
      fontFamily: "Plus Jakarta Sans",
      borderRadius: 20,
      shadow: "subtle",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Forest",
    theme: {
      formBgColor: "#052E16",
      formTextColor: "#DCFCE7",
      accentColor: "#4ADE80",
      inputBgColor: "#14532D",
      inputBorderColor: "#166534",
      inputTextColor: "#DCFCE7",
      secondaryTextColor: "#86EFAC",
      fontFamily: "Space Grotesk",
      borderRadius: 8,
      shadow: "subtle",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Lavender",
    theme: {
      formBgColor: "#FAF5FF",
      formTextColor: "#3B0764",
      accentColor: "#A855F7",
      inputBgColor: "#F3E8FF",
      inputBorderColor: "#D8B4FE",
      inputTextColor: "#3B0764",
      secondaryTextColor: "#7E22CE",
      fontFamily: "Poppins",
      borderRadius: 24,
      shadow: "subtle",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Slate Pro",
    theme: {
      formBgColor: "#1E293B",
      formTextColor: "#F1F5F9",
      accentColor: "#3B82F6",
      inputBgColor: "#334155",
      inputBorderColor: "#475569",
      inputTextColor: "#F1F5F9",
      secondaryTextColor: "#94A3B8",
      fontFamily: "Inter",
      borderRadius: 10,
      shadow: "medium",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
  {
    name: "Glassmorphism",
    theme: {
      formBgColor: "#1A1A2E",
      formTextColor: "#FFFFFF",
      accentColor: "#E879F9",
      inputBgColor: "#2A2A3E",
      inputBorderColor: "#3A3A4E",
      inputTextColor: "#FFFFFF",
      secondaryTextColor: "#C084FC",
      fontFamily: "DM Sans",
      borderRadius: 20,
      shadow: "strong",
      cardMaxWidth: 432,
      cardPadding: "default",
      successMessage: "Thank you for your feedback!",
      showConfetti: true,
      successRedirectUrl: null,
      successCtaText: null,
      successCtaUrl: null,
      buttonText: "Send Feedback",
    },
  },
];
